// Warm Linen — a slick editorial light theme.
// Warm paper canvas, ink text, a single terracotta accent, hairline borders.
// Every required THEME_TOKEN_NAMES entry has a concrete, self-contained value.
export default {
  // Canvas & surfaces
  canvas: '#FBF7F0',
  surface: '#FFFDF9',
  surfaceSubtle: '#F5EFE4',
  surfaceRaised: '#FFFDF9',
  surfaceTint: '#FBEDE4',
  scrim: 'rgb(40 30 20 / 46%)',

  // Text & icons
  text: '#1C1A17',
  textSecondary: '#4A443C',
  textMuted: '#6E675C',
  textInverse: '#FBF7F0',
  link: '#B4460E',
  icon: '#4A443C',
  iconMuted: '#8A8272',

  // Borders & focus
  border: '#E7DFD2',
  borderStrong: '#D6CBB8',
  borderInteractive: '#B3A794',
  focusRing: '#C2410C',
  selection: 'rgb(194 65 12 / 20%)',

  // Accent (terracotta)
  accent: '#C2410C',
  accentHover: '#A5370A',
  accentPressed: '#822B07',
  onAccent: '#FFFFFF',
  accentSubtle: '#FBEADF',
  onAccentSubtle: '#8C2F08',

  // Semantic feedback
  info: '#2A6BB0',
  onInfo: '#FFFFFF',
  infoSubtle: '#E6EFF7',
  success: '#4E7A38',
  onSuccess: '#FFFFFF',
  successSubtle: '#ECF2E4',
  warning: '#B4690E',
  onWarning: '#FFFFFF',
  warningSubtle: '#FBEED6',
  danger: '#B3261E',
  onDanger: '#FFFFFF',
  dangerSubtle: '#F8E3E0',

  // Controls & fields
  control: '#FFFDF9',
  controlHover: '#F5EFE4',
  controlPressed: '#ECE3D4',
  controlDisabled: '#EFE9DE',
  controlText: '#1C1A17',
  controlTextDisabled: '#9B9384',
  field: '#FFFDF9',
  fieldHover: '#FCF9F3',
  fieldInvalid: '#B3261E',

  // Task statuses
  statusNeutral: '#6E675C',
  statusNeutralSubtle: '#EFE9DE',
  onStatusNeutral: '#4A443C',
  statusRunning: '#2A6BB0',
  statusRunningSubtle: '#E6EFF7',
  onStatusRunning: '#1E4E80',
  statusWaiting: '#B4690E',
  statusWaitingSubtle: '#FBEED6',
  onStatusWaiting: '#8A4F09',
  statusSuccess: '#4E7A38',
  statusSuccessSubtle: '#ECF2E4',
  onStatusSuccess: '#3B5E2A',
  statusWarning: '#B4690E',
  statusWarningSubtle: '#FBEED6',
  onStatusWarning: '#8A4F09',
  statusDanger: '#B3261E',
  statusDangerSubtle: '#F8E3E0',
  onStatusDanger: '#8C1D17',

  // Code & diff
  codeCanvas: '#F7F1E7',
  codeText: '#2A2621',
  codeMuted: '#6E675C',
  codeBorder: '#E7DFD2',
  diffAdded: '#4E7A38',
  diffAddedSubtle: '#E9F1E1',
  diffRemoved: '#B3261E',
  diffRemovedSubtle: '#F8E1DE',
  diffChanged: '#9A6512',
  diffChangedSubtle: '#FBEED6',

  // Terminal
  terminalBackground: '#FCF8F1',
  terminalForeground: '#2A2621',
  terminalCursor: '#C2410C',
  terminalCursorAccent: '#FCF8F1',
  terminalSelectionBackground: 'rgb(194 65 12 / 22%)',
  terminalSelectionForeground: '#1C1A17',
  terminalBlack: '#2A2621',
  terminalRed: '#B3261E',
  terminalGreen: '#4E7A38',
  terminalYellow: '#9A6512',
  terminalBlue: '#2A6BB0',
  terminalMagenta: '#8A4E9E',
  terminalCyan: '#1E7A78',
  terminalWhite: '#6E675C',
  terminalBrightBlack: '#4A443C',
  terminalBrightRed: '#C63A2E',
  terminalBrightGreen: '#5E8F44',
  terminalBrightYellow: '#B4790E',
  terminalBrightBlue: '#3A80C6',
  terminalBrightMagenta: '#A063B4',
  terminalBrightCyan: '#2A928E',
  terminalBrightWhite: '#8A8272',

  // Geometry & spacing
  borderWidth: '1px',
  focusWidth: '2px',
  radiusControl: '8px',
  radiusContainer: '12px',
  radiusOverlay: '16px',
  radiusShell: '24px',
  radiusRound: '9999px',
  controlHeightCompact: '28px',
  controlHeight: '36px',
  controlHeightTouch: '44px',
  space1: '2px',
  space2: '4px',
  space3: '6px',
  space4: '8px',
  space5: '12px',
  space6: '16px',
  space7: '24px',
  space8: '32px',
  space9: '48px',

  // Typography
  fontSans: "'Inter', ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif",
  fontMono: "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
  textXs: '11px',
  textSm: '12px',
  textMd: '14px',
  textLg: '16px',
  textXl: '20px',
  lineHeightXs: '1.35',
  lineHeightSm: '1.4',
  lineHeightMd: '1.55',
  lineHeightLg: '1.5',
  lineHeightXl: '1.25',
  weightRegular: '400',
  weightMedium: '500',
  weightSemibold: '600',

  // Elevation & motion (warm-tinted shadows, unhurried easings)
  shadowSurface: '0 1px 2px rgb(60 40 20 / 8%)',
  shadowRaised: '0 6px 20px rgb(60 40 20 / 12%)',
  shadowOverlay: '0 24px 60px rgb(60 40 20 / 20%)',
  durationPress: '90ms',
  durationFast: '150ms',
  durationStandard: '220ms',
  durationDeliberate: '320ms',
  easeStandard: 'cubic-bezier(0.2, 0, 0, 1)',
  easeEnter: 'cubic-bezier(0.16, 1, 0.3, 1)',
  easeExit: 'cubic-bezier(0.4, 0, 1, 1)',
}
